name: 'Publish Github Release'
description: Publish jDeploy Bundles on Github

inputs:

  release_tag:
    description: The release tag
    required: true
  github_token:
    description: Github token
    required: true


runs:
  using: composite
  steps:
    - name: Set up Git Config
      shell: bash
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Publish with jDeploy
      shell: bash
      run: |
        npm version "${{ inputs.release_tag }}"
        npx jdeploy github-prepare-release
    - name: Publish package-info.json
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ inputs.github_token }}"
        automatic_release_tag: "jdeploy"
        prerelease: false
        title: "jDeploy Package Info"
        files: ./jdeploy/github-release-files/package-info.json
    - name: Upload Files to Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        file: "./jdeploy/github-release-files/*"
        tags: true


