#!/bin/bash
set -e
cd TextEditor
bash test.sh
cd ../TextEditor2
bash test.sh
cd ../TextEditor3
bash test.sh
cd ../TextEditor4
bash test.sh
cd ../TextEditor5
bash test.sh
cd ../TextEditor6
bash test.sh
cd ../TextEditor7
bash test.sh
cd ../TextEditorCodesign
bash test.sh
cd ../TextEditorBundleJRECodesign
bash test.sh
cd ../TextEditorBundleJRECodesignDMG
bash test.sh
cd ../LauncherTest1
bash test.sh