package ca.weblite.jdeploy.gui.tabs;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class DetailsPanel {
    private JPanel panel1;
    private JTextField name;
    private JTextField version;
    private JTextField title;
    private JTextField author;
    private JTextArea description;
    private JButton icon;
    private JButton helpButton;
    private JTextField jarFile;
    private JComboBox javaVersion;
    private JCheckBox requiresJavaFX;
    private JCheckBox requiresFullJDK;
    private JButton selectJarFile;
    private JTextField homepage;
    private JButton verifyButton;
    private JTextField repositoryUrl;
    private JTextField repositoryDirectory;
    private JTextField license;
    private JPanel root;

    public JPanel getRoot() {
        return root;
    }

    public JTextField getName() {
        return name;
    }

    public JTextField getVersion() {
        return version;
    }

    public JTextField getTitle() {
        return title;
    }

    public JTextField getAuthor() {
        return author;
    }

    public JTextArea getDescription() {
        return description;
    }

    public JButton getIcon() {
        return icon;
    }

    public JButton getHelpButton() {
        return helpButton;
    }

    public JTextField getJarFile() {
        return jarFile;
    }

    public JComboBox getJavaVersion() {
        return javaVersion;
    }

    public JCheckBox getRequiresJavaFX() {
        return requiresJavaFX;
    }

    public JCheckBox getRequiresFullJDK() {
        return requiresFullJDK;
    }

    public JButton getSelectJarFile() {
        return selectJarFile;
    }

    public JTextField getHomepage() {
        return homepage;
    }

    public JButton getVerifyButton() {
        return verifyButton;
    }

    public JTextField getRepositoryUrl() {
        return repositoryUrl;
    }

    public JTextField getRepositoryDirectory() {
        return repositoryDirectory;
    }

    public JTextField getLicense() {
        return license;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new BorderLayout(0, 0));
        root.setPreferredSize(new Dimension(640, 500));
        root.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        root.add(panel1, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setText("Name");
        CellConstraints cc = new CellConstraints();
        panel1.add(label1, cc.xy(1, 1));
        name = new JTextField();
        panel1.add(name, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        label2.setText("Version");
        panel1.add(label2, cc.xy(1, 3));
        version = new JTextField();
        panel1.add(version, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        title = new JTextField();
        panel1.add(title, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        label3.setText("Title");
        panel1.add(label3, cc.xy(1, 5));
        final JLabel label4 = new JLabel();
        label4.setText("Author");
        panel1.add(label4, cc.xy(1, 7));
        author = new JTextField();
        panel1.add(author, cc.xy(3, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label5 = new JLabel();
        label5.setText("Description");
        panel1.add(label5, cc.xy(1, 9));
        final JLabel label6 = new JLabel();
        label6.setText("License");
        panel1.add(label6, cc.xy(1, 11));
        license = new JTextField();
        panel1.add(license, cc.xy(3, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, cc.xy(3, 9, CellConstraints.FILL, CellConstraints.FILL));
        description = new JTextArea();
        description.setRows(3);
        scrollPane1.setViewportView(description);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        root.add(panel2, BorderLayout.NORTH);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        root.add(panel3, BorderLayout.SOUTH);
        jarFile = new JTextField();
        panel3.add(jarFile, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label7 = new JLabel();
        label7.setText("JAR File");
        panel3.add(label7, cc.xy(1, 3));
        final JLabel label8 = new JLabel();
        label8.setText("Java Version");
        panel3.add(label8, cc.xy(1, 5));
        javaVersion = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("21");
        defaultComboBoxModel1.addElement("20");
        defaultComboBoxModel1.addElement("17");
        defaultComboBoxModel1.addElement("11");
        defaultComboBoxModel1.addElement("8");
        javaVersion.setModel(defaultComboBoxModel1);
        panel3.add(javaVersion, cc.xy(3, 5));
        requiresJavaFX = new JCheckBox();
        requiresJavaFX.setText("Requires JavaFX");
        panel3.add(requiresJavaFX, cc.xy(3, 7));
        requiresFullJDK = new JCheckBox();
        requiresFullJDK.setText("Requires Full JDK");
        panel3.add(requiresFullJDK, cc.xy(3, 9));
        final JLabel label9 = new JLabel();
        label9.setText("Homepage");
        panel3.add(label9, cc.xy(1, 11));
        selectJarFile = new JButton();
        selectJarFile.setText("Select...");
        panel3.add(selectJarFile, cc.xy(5, 3));
        homepage = new JTextField();
        panel3.add(homepage, cc.xy(3, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        verifyButton = new JButton();
        verifyButton.setText("Verify");
        panel3.add(verifyButton, cc.xy(5, 11));
        final JLabel label10 = new JLabel();
        label10.setText("Repository");
        panel3.add(label10, cc.xy(1, 13));
        repositoryUrl = new JTextField();
        panel3.add(repositoryUrl, cc.xy(3, 13, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label11 = new JLabel();
        label11.setText("Directory:");
        panel3.add(label11, cc.xy(3, 15));
        repositoryDirectory = new JTextField();
        panel3.add(repositoryDirectory, cc.xy(3, 17, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(10, 10));
        root.add(panel4, BorderLayout.WEST);
        panel4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        icon = new JButton();
        icon.setText("");
        panel4.add(icon, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
