# This workflow will build a Java project with Gradle and bundle them as native app installers with jDeploy
# See https://www.jdeploy.com for more information.

name: jDeploy CI with Gradle

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]

# Prevent concurrent jDeploy workflows to avoid race conditions
concurrency:
  group: jdeploy-${{ github.repository }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK #{{ JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: '#{{ JAVA_VERSION }}'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Build App Installer Bundles
        uses: shannah/jdeploy@#{{ JDEPLOY_VERSION }}
        with:
          github_token: ${{ github.token }}