# This workflow will build a Java project with Maven and bundle them as native app installers with jDeploy
# See https://www.jdeploy.com for more information.

name: jDeploy CI with Maven

on:
  push:
    branches: ['*']
    tags: ['*']

# Prevent concurrent jDeploy workflows to avoid race conditions
concurrency:
  group: jdeploy-${{ github.repository }}
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK #{{ JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: '#{{ JAVA_VERSION }}'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build App Installer Bundles
        uses: shannah/jdeploy@#{{ JDEPLOY_VERSION }}
        with:
          github_token: ${{ github.token }}
