name: Run Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test-linux-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '8', '11', '17' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Test Linux
        env:
          JDEPLOY_TEST_JVM_DOWNLOADS: true
        run: bash build_and_test.sh


  build-mac-x64:
    runs-on: macos-latest
    strategy:
      matrix:
        java-version: [ '11', '17']
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Test Mac
        env:
          JDEPLOY_TEST_JVM_DOWNLOADS: true
        run: bash build_and_test.sh


  build-win-x64:
    runs-on: windows-latest
    strategy:
      matrix:
        java-version: [ '8', '11', '17' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '24'
      - name: Verify Node.js installation
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Print PATH and verify npm
        run: |
          echo "PATH: $PATH"
          echo "NODE_PATH: $NODE_PATH"

      - name: Build Windows
        env:
          JDEPLOY_TEST_JVM_DOWNLOADS: true
        run: bash build_and_test.sh
        shell: bash

  build-win-arm:
    runs-on: windows-11-arm
    strategy:
      matrix:
        java-version: [ '17' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '24'
      - name: Verify Node.js installation
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Print PATH and verify npm
        run: |
          echo "PATH: $PATH"
          echo "NODE_PATH: $NODE_PATH"

      - name: Build Windows
        env:
          JDEPLOY_TEST_JVM_DOWNLOADS: true
        run: bash build_and_test.sh
        shell: bash
