name: Test Mac Notarization

on:
  push:
    branches: [ master ]

jobs:
        
  test-notarize-mac:
    if: false
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Install MacOS Certificates
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
        p12-password: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}

    - name: Test Mac
      env:
        JDEPLOY_MAC_NOTARIZATION_PASSWORD: ${{ secrets.JDEPLOY_MAC_TEST_NOTARIZATION_PASSWORD }}
        JDEPLOY_MAC_DEVELOPER_ID: ${{ secrets.APPLE_ID }}
        JDEPLOY_MAC_DEVELOPER_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        JDEPLOY_MAC_DEVELOPER_CERTIFICATE_NAME: ${{ secrets.DEVELOPER_ID_CERTIFICATE_NAME }}
        JDEPLOY_TEST_CERTIFICATE_NAME: ${{ secrets.DEVELOPER_ID_CERTIFICATE_NAME }}
      run: bash build_and_test.sh